program DelphiRagAgent;



uses
  System.StartUpCopy,
  FMX.Forms,
  uNativeHttpControl in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uNativeHttpControl.pas',
  uAPPCommon in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uAPPCommon.pas',
  uAndroidLog in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\Android\uAndroidLog.pas',
  FlyUtils.Android.PostRunnableAndTimer in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\FlyUtils.Android.PostRunnableAndTimer.pas',
  uIdHttpControl in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uIdHttpControl.pas',
  uGetDeviceInfo in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uGetDeviceInfo.pas',
  HzSpell in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\HzSpell\HzSpell.pas',
  MainForm in 'MainForm.pas' {frmMain},
  FlyFmxUtils in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\FlyFmxUtils.pas',
  Android.JNI.Toast in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\Android.JNI.Toast.pas',
  Androidapi.JNI.ActivityManager in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\Androidapi.JNI.ActivityManager.pas',
  Androidapi.JNI.android.os.storage.StorageManager in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\Androidapi.JNI.android.os.storage.StorageManager.pas',
  Androidapi.JNI.Environment in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\Androidapi.JNI.Environment.pas',
  Androidapi.JNI.java.lang.FlyUtils in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\Androidapi.JNI.java.lang.FlyUtils.pas',
  Androidapi.JNI.StatFs in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\Androidapi.JNI.StatFs.pas',
  Androidapi.JNI.Stream2 in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\Androidapi.JNI.Stream2.pas',
  Androidapi.JNI.ToastForService in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FlyFilesUtils\Androidapi.JNI.ToastForService.pas',
  uImageCode in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uImageCode.pas',
  CommonImageDataMoudle in 'CommonImageDataMoudle.pas' {dmCommonImageDataMoudle: TDataModule},
  MyFrame in 'MyFrame.pas' {FrameMy: TFrame},
  uConst in 'uConst.pas',
  ShopingFrame in 'ShopingFrame.pas' {FrameShoping: TFrame},
  DelphiClientMainForm in 'DelphiClientMainForm.pas' {frmOrangeUIClientMain},
  UserBalanceFrame in 'UserBalanceFrame.pas' {FrameUserBalance: TFrame},
  PayOrderFrame in 'PayOrderFrame.pas' {FramePayOrder: TFrame},
  TakeOrderFrame in 'TakeOrderFrame.pas' {FrameTakeOrder: TFrame},
  OrderInfoFrame in 'OrderInfoFrame.pas' {FrameOrderInfo: TFrame},
  UserOrderListFrame in 'UserOrderListFrame.pas' {FrameUserOrderList: TFrame},
  Androidapi.JNI.wxapi in 'Androidapi.JNI.wxapi.pas',
  ShopInfoFrame in 'ShopInfoFrame.pas' {FrameShopInfo: TFrame},
  ShopGoodsListFrame in 'ShopGoodsListFrame.pas' {FrameShopGoodsList: TFrame},
  ShopAddUserCarFrame in 'ShopAddUserCarFrame.pas' {FrameShopAddUserCar: TFrame},
  ShopGoodsInfoFrame in 'ShopGoodsInfoFrame.pas' {FrameShopGoodsInfo: TFrame},
  AddCarGoodsFrame in 'AddCarGoodsFrame.pas' {FrameAddCarGoods: TFrame},
  GoodsListFrame in 'GoodsListFrame.pas' {FrameGoodsList: TFrame},
  PayOrderCommonFrame in 'PayOrderCommonFrame.pas' {FramePayOrderCommon: TFrame},
  uAndroidPermission_D10_2 in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uAndroidPermission_D10_2.pas',
  iOSApi.ContactsUI in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\IOS\iOSApi.ContactsUI.pas',
  iOSApi.CNContact in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\IOS\Contacts\iOSApi.CNContact.pas',
  iOSApi.CNLabeledValue in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\IOS\Contacts\iOSApi.CNLabeledValue.pas',
  iOSApi.CNPhoneNumber in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\IOS\Contacts\iOSApi.CNPhoneNumber.pas',
  iOSApi.CNContactPickerViewController in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\IOS\iOSApi.CNContactPickerViewController.pas',
  EasyServiceCommonMaterialDataMoudle in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\EasyServiceCommonMaterialDataMoudle.pas' {dmEasyServiceCommonMaterial: TDataModule},
  uGPSLocation in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uGPSLocation.pas',
  uMapCommon in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uMapCommon.pas',
  uDataSetToJson in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uDataSetToJson.pas',
  UpdateFrame in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\CommonFrames\UpdateFrame.pas',
  uVersionChecker in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uVersionChecker.pas',
  uSkinItemJsonHelper in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uSkinItemJsonHelper.pas',
  uVirtualListDataController in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uVirtualListDataController.pas',
  uPushClientRestImpl in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uPushClientRestImpl.pas',
  uRestInterfaceCall in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uRestInterfaceCall.pas',
  PopupMenuFrame in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\CommonFrames\PopupMenuFrame.pas',
  SelectAreaFrame in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\CommonFrames\SelectAreaFrame.pas',
  uDataInterface in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uDataInterface.pas',
  SideMenuFrame in 'SideMenuFrame.pas' {FrameSideMenu},
  FMX.Platform.iOS in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FMX.Platform.iOS.pas',
  FMX.FontGlyphs.iOS in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FMX.FontGlyphs.iOS.pas',
  FMX.DeviceInfo in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FMX.DeviceInfo.pas',
  FMX.Context.GLES.iOS in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\FMX.Context.GLES.iOS.pas',
  uBaseThirdPartyAccountAuth in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uBaseThirdPartyAccountAuth.pas',
  ListItemStyleFrame_SaleManageOrderFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_SaleManageOrderFrame.pas',
  ListItemStyleFrame_GoodsManageFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_GoodsManageFrame.pas',
  ListItemStyleFrame_UserSerivceGoodsVIPFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_UserSerivceGoodsVIPFrame.pas' {FrameListItemStyle_UserSerivceGoodsVIP},
  ListItemStyleFrame_UserSerivceGoodsVIPRightsFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_UserSerivceGoodsVIPRightsFrame.pas',
  uOpenCommon in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uOpenCommon.pas',
  uModule_InterfaceSign in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uModule_InterfaceSign.pas',
  BaiduWebMapFrame in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\CommonFrames\BaiduWebMapFrame.pas',
  ListItemStyleFrame_RadioButton in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_RadioButton.pas',
  RegisterFrame in 'RegisterFrame\RegisterFrame.pas',
  FileMessageFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\FileMessageFrame.pas',
  ListItemStyleFrame_HeaderInfo in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_HeaderInfo.pas',
  SendEmotionFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\SendEmotionFrame.pas',
  SendMyEmotionFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\SendMyEmotionFrame.pas',
  SendMyFileFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\SendMyFileFrame.pas',
  AddContentFrame in 'Community\AddContentFrame.pas',
  ContentClassifyFrame in 'Community\ContentClassifyFrame.pas',
  ContentInfoFrame in 'Community\ContentInfoFrame.pas',
  ContentListFrame in 'Community\ContentListFrame.pas',
  UserLikeContentListFrame in 'Community\UserLikeContentListFrame.pas',
  ContentTopicListFrame in 'Community\ContentTopicListFrame.pas',
  uContentOperation in 'Community\uContentOperation.pas',
  UserListFrame in 'UserListFrame.pas',
  SaveDraftFrame in 'Community\SaveDraftFrame.pas',
  SelectPictureFrame in 'SelectPictureFrame.pas',
  uSelectMediaDialog in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uSelectMediaDialog.pas',
  SelectGroupsContentTypeFrame in 'Community\SelectGroupsContentTypeFrame.pas',
  SendMyImageFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\SendMyImageFrame.pas' {FrameSendMyImage: TFrame},
  SendImageFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\SendImageFrame.pas' {FrameSendImage: TFrame},
  MyChatDialogFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\MyChatDialogFrame.pas' {FrameMyChatDialog: TFrame},
  ListItemStyleFrame_SimpleInvitation in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_SimpleInvitation.pas' {FrameListItemStyle_SimpleInvitation: TFrame},
  ListItemStyleFrame_SimpleGroupMember in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_SimpleGroupMember.pas' {FrameListItemStyle_SimpleGroupMember: TFrame},
  ListItemStyleFrame_SimpleGameInfo2 in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_SimpleGameInfo2.pas' {FrameListItemStyle_SimpleGameInfo2: TFrame},
  ListItemStyleFrame_SimpleGameInfo in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_SimpleGameInfo.pas' {FrameListItemStyle_SimpleGameInfo: TFrame},
  ListItemStyleFrame_SimpleContact in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_SimpleContact.pas' {FrameListItemStyle_SimpleContact: TFrame},
  ListItemStyleFrame_SelectContact in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_SelectContact.pas' {FrameListItemStyle_SelectContact: TFrame},
  ListItemStyleFrame_RecentContact in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_RecentContact.pas' {FrameListItemStyle_RecentContact: TFrame},
  ListItemStyleFrame_GroupMemberFooter in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_GroupMemberFooter.pas' {FrameListItemStyle_GroupMemberFooter: TFrame},
  ListItemStyleFrame_GroupMember in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_GroupMember.pas' {FrameListItemStyle_GroupMember: TFrame},
  ListItemStyleFrame_GameInfoDetails2 in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_GameInfoDetails2.pas' {FrameListItemStyle_GameInfoDetails2: TFrame},
  ListItemStyleFrame_GameInfoDetails in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_GameInfoDetails.pas' {FrameListItemStyle_GameInfoDetails: TFrame},
  ListItemStyleFrame_AddContact in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ListItemStyleFrame_AddContact.pas' {FrameAddContactListItemStyle: TFrame},
  ChatDialogFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ChatDialogFrame.pas' {FrameChatDialog: TFrame},
  ChatCreatTime in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\IM\ChatCreatTime.pas' {FrameChatCreatTime: TFrame},
  ListItemStyleFrame_YCLiving_TelRecord in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_YCLiving_TelRecord.pas' {FrameListItemStyle_YCLiving_TelRecord: TFrame},
  ListItemStyleFrame_YCLiving_RechargeOption in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_YCLiving_RechargeOption.pas' {FrameListItemStyle_YCLiving_RechargeOption: TFrame},
  ListItemStyleFrame_YCLiving_CaptionTopDetailLeft in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_YCLiving_CaptionTopDetailLeft.pas' {FrameListItemStyle_YCLiving_CaptionTopDetailLeft: TFrame},
  ListItemStyleFrame_ThemeColorButton in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_ThemeColorButton.pas' {FrameListItemStyle_ThemeColorButton: TFrame},
  ListItemStyleFrame_SmallCoupon in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_SmallCoupon.pas' {FrameSmallCouponListItemStyle: TFrame},
  ListItemStyleFrame_SearchBar_BottomMargin in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_SearchBar_BottomMargin.pas' {FrameListItemStyle_SearchBar_BottomMargin: TFrame},
  ListItemStyleFrame_SearchBar in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_SearchBar.pas' {FrameListItemStyle_SearchBar: TFrame},
  ListItemStyleFrame_PopupMenuItem in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_PopupMenuItem.pas' {FrameListItemStyle_PopupMenuItem: TFrame},
  ListItemStyleFrame_ItemDevide in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_ItemDevide.pas' {FrameListItemStyle_ItemDevide: TFrame},
  ListItemStyleFrame_ImageListViewer in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_ImageListViewer.pas' {FrameImageListViewerListItemStyle: TFrame},
  ListItemStyleFrame_IconTopCenter_CaptionBottomCenter_Selected in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconTopCenter_CaptionBottomCenter_Selected.pas' {FrameListItemStyle_IconTopCenter_CaptionBottomCenter_Selected: TFrame},
  ListItemStyleFrame_IconTopCenter_CaptionBottomCenterWhite in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconTopCenter_CaptionBottomCenterWhite.pas' {FrameListItemStyle_IconTopCenter_CaptionBottomCenterWhite: TFrame},
  ListItemStyleFrame_IconTopCenter_CaptionBottomCenterBlack in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconTopCenter_CaptionBottomCenterBlack.pas' {FrameListItemStyle_IconTopCenter_CaptionBottomCenterBlack: TFrame},
  ListItemStyleFrame_IconCaption_RightGrayDetail in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconCaption_RightGrayDetail.pas' {FrameIconCaption_RightGrayDetailListItemStyle: TFrame},
  ListItemStyleFrame_IconCaption_BottomDetail_Service_Item_Book in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconCaption_BottomDetail_Service_Item_Book.pas' {FrameIconCaption_BottomDetail_Service_Item_BookListItemStyle: TFrame},
  ListItemStyleFrame_IconCaption_BottomDetail_RightGrayDetail1 in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconCaption_BottomDetail_RightGrayDetail1.pas' {FrameIconCaption_BottomDetail_RightGrayDetail1ListItemStyle: TFrame},
  ListItemStyleFrame_IconCaptionMultiColor in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconCaptionMultiColor.pas' {FrameListItemStyle_IconCaptionMultiColor: TFrame},
  ListItemStyleFrame_IconCaption in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconCaption.pas' {FrameIconCaptionListItemStyle: TFrame},
  ListItemStyleFrame_HorzListBox in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_HorzListBox.pas' {FrameListItemStyle_HorzListBox: TFrame},
  ListItemStyleFrame_HorzImageListBox in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_HorzImageListBox.pas' {FrameListItemStyle_HorzImageListBox: TFrame},
  ListItemStyleFrame_Group in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_Group.pas' {FrameListItemStyle_Group: TFrame},
  ListItemStyleFrame_ContentCommentDetail in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_ContentCommentDetail.pas' {FrameContentCommentDetailListItemStyle: TFrame},
  ListItemStyleFrame_CommentDetail in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_CommentDetail.pas' {FrameCommentDetailListItemStyle: TFrame},
  ListItemStyleFrame_Comment in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_Comment.pas' {FrameCommentListItemStyle: TFrame},
  ListItemStyleFrame_CarglSelectRepairMaterial in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_CarglSelectRepairMaterial.pas' {FrameCarglSelectRepairMaterialListItemStyle: TFrame},
  ListItemStyleFrame_CarglSelectRepairItem in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_CarglSelectRepairItem.pas' {FrameCarglSelectRepairItemListItemStyle: TFrame},
  ListItemStyleFrame_Caption_DelButton in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_Caption_DelButton.pas' {FrameListItemStyle_Caption_DelButton: TFrame},
  ListItemStyleFrame_Caption_BottomDetail_IconRight in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_Caption_BottomDetail_IconRight.pas' {FrameListItemStyle_Caption_BottomDetail_IconRight: TFrame},
  ListItemStyleFrame_CaptionTopDetailBottom in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_CaptionTopDetailBottom.pas' {FrameListItemStyle_CaptionTopDetailBottom: TFrame},
  ListItemStyleFrame_CaptionTop16_DetailBottom in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_CaptionTop16_DetailBottom.pas' {FrameListItemStyle_CaptionTop16_DetailBottom: TFrame},
  ListItemStyleFrame_CaptionRightCheckBox in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_CaptionRightCheckBox.pas' {FrameListItemStyle_CaptionRightCheckBox: TFrame},
  ListItemStyleFrame_CaptionLeft_DetailRight_Accessory in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_CaptionLeft_DetailRight_Accessory.pas' {FrameListItemStyle_CaptionLeft_DetailRight_Accessory: TFrame},
  ListItemStyleFrame_CaptionGrayCenter in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_CaptionGrayCenter.pas' {FrameListItemStyle_CaptionGrayCenter: TFrame},
  ListItemStyleFrame_Base in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_Base.pas' {FrameBaseListItemStyleBase: TFrame},
  ListItemStyleFrame_4Buttons in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_4Buttons.pas' {FrameListItemStyle_4Buttons: TFrame},
  BaseParentItemStyleFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\BaseParentItemStyleFrame.pas' {FrameBaseParentItemStyle: TFrame},
  BaseListItemStyleFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\BaseListItemStyleFrame.pas' {FrameBaseListItemStyle: TFrame},
  ListItemStyleFrame_ShortVideo in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_ShortVideo.pas' {FrameShortVideoListItemStyle: TFrame},
  ListItemStyleFrame_ShopEvalvateFrame in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_ShopEvalvateFrame.pas' {FrameListItemStyle_ShopEvalvate: TFrame},
  ListItemStyleFrame_News in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_News.pas' {FrameListItemStyle_News: TFrame},
  ListItemStyleFrame_LiveStream in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_LiveStream.pas' {FrameListItemStyle_LiveStream: TFrame},
  ListItemStyleFrame_DelphiContent in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_DelphiContent.pas' {FrameDelphiContentListItemStyle: TFrame},
  ListItemStyleFrame_ContentSuggestNews in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_ContentSuggestNews.pas' {FrameContentSuggestNewsListItemStyle: TFrame},
  ListItemStyleFrame_ContentNews in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_ContentNews.pas' {FrameContentNewsListItemStyle: TFrame},
  ListItemStyleFrame_XFOnlineNews in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\XFOnLine\ListItemStyleFrame_XFOnlineNews.pas' {FrameXFOnlineNewsListItemStyle: TFrame},
  ListItemStyleFrame_SignDay in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\XFOnLine\ListItemStyleFrame_SignDay.pas' {FrameListItemStyle_SignDay: TFrame},
  ListItemStyleFrame_ScoreRecharge in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\XFOnLine\ListItemStyleFrame_ScoreRecharge.pas' {FrameListItemStyle_ScoreRecharge: TFrame},
  ListItemStyleFrame_ScoreExchangeActivity in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\XFOnLine\ListItemStyleFrame_ScoreExchangeActivity.pas' {FrameListItemStyle_ScoreExchangeActivity: TFrame},
  ListItemStyleFrame_MyGameGiftPackage in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\XFOnLine\ListItemStyleFrame_MyGameGiftPackage.pas' {FrameListItemStyle_MyGameGiftPackage: TFrame},
  ListItemStyleFrame_GameList in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\XFOnLine\ListItemStyleFrame_GameList.pas' {FrameListItemStyle_GameList: TFrame},
  ListItemStyleFrame_GameGiftPackage in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\XFOnLine\ListItemStyleFrame_GameGiftPackage.pas' {FrameListItemStyle_GameGiftPackage: TFrame},
  ListItemStyleFrame_GameActivity in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\XFOnLine\ListItemStyleFrame_GameActivity.pas' {FrameListItemStyle_GameActivity: TFrame},
  MainFrame in 'MainFrame.pas',
  HomeFrame in 'HomeFrame.pas',
  MyScoreFrame in 'MyScoreFrame.pas',
  ListItemStyleFrame_WorkOrderContent in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\DCommunity\ListItemStyleFrame_WorkOrderContent.pas',
  uOpenClientCommon in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uOpenClientCommon.pas',
  uViewPictureListFrame in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\uViewPictureListFrame.pas',
  iOSapi.Photos.Manager in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\MultiSelectPhotos\iOSapi.Photos.Manager.pas',
  iOSapi.Photos in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\MultiSelectPhotos\iOSapi.Photos.pas',
  uPhotoManager.Android in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\MultiSelectPhotos\uPhotoManager.Android.pas',
  uPhotoManager.iOS in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\MultiSelectPhotos\uPhotoManager.iOS.pas',
  uPhotoManager in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\MultiSelectPhotos\uPhotoManager.pas',
  uPhotoManager.Windows in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\MultiSelectPhotos\uPhotoManager.Windows.pas',
  uRestIntfMemTable in 'D:\MyFilesNew\OrangeUI\OrangeProjectCommon\RestIntfMemTable\uRestIntfMemTable.pas',
  ListItemStyleFrame_IconNotice in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconNotice.pas',
  LoginFrame in 'LoginFrame.pas' {FrameLogin: TFrame},
  ListItemStyleFrame_IconTopCenterBackColor_CaptionBottomCenterBlack in 'D:\MyFilesNew\OrangeUI\OrangeUIStyles\ListItemStyleFrame_IconTopCenterBackColor_CaptionBottomCenterBlack.pas';

{$R *.res}

begin
//  //主题色 蓝色
//  uGraphicCommon.SkinThemeColor:=$FF3CB371;
//  //绿色
//  uGraphicCommon.SkinThemeColor1:=$FF3CB371;

  ReportMemoryLeaksONShutdown:=DebugHook<>0;

  Application.Initialize;
//  Application.FormFactor.Orientations := [TFormOrientation.Portrait];
  Application.CreateForm(TdmEasyServiceCommonMaterial, dmEasyServiceCommonMaterial);
  Application.CreateForm(TdmCommonImageDataMoudle, dmCommonImageDataMoudle);
  Application.CreateForm(TfrmOrangeUIClientMain, frmOrangeUIClientMain);
  Application.Run;
end.


